---
title: "Consumer Resource Model - parameters"
author: "Daniel Garza"
date: "1/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### randomE

**`n_species`** : `Integer`

number of species in community

**`n_resources`** : `integer`

number of compounds that are either consumed or produced by the community members

**`names_species`** : `character vector`

names of species to use during the simulation. If not provided, species are named as *sp1, sp2, ...*

must have same length as `n_species`

**`names_resources`** : `character vector`

names of compounds to use during the simulation. If not provided, compounds are named as *res1, res2, ...*

must have same length as `n_resources`

**`mean_consumption`** : `numeric`

Average number of compounds that are required for the growth of each species. This is determined by sampling from a Poisson distribution with $\lambda$ = `mean_consumption`.

The default values is one fourth of `n_resources`

**`mean_production`** : `numeric`

Average number of compounds that are released as by-product from the growth of each species. This is determined by sampling from a Poisson distribution with $\lambda$ = `mean_production`.

The default values is one sixth of `n_resources`

**`maintenance`** : `numeric`

fraction of the consumption fluxes that are channeled into the organism's growth and maintenance, which constrains the sum of fluxes of the metabolic by-products.

default is 0.5 (see example 3 for more detail).

**`trophic_levels`** : `integer`

Hierarchical allocation of species into trophic groups. The input should be a list of integers allocating the total `n_species` into groups (see example 6).

For example, a community with 10 species can have a distribution of `c(3,4,3)`, meaning the secretion products of the three first species are preferred by the next four, while the secretion products of these four are preferred by the last three.

**`trophic_preferences`** : `list`

A list of trophic preferences for each level. Each element in this list should have a same length of `n_resources` , indicating the strength of consumption(positive) or production(negative) of resources in each trophic level. NULL indicates that in this trophic level, there's no preferred materials as nutrient or product.

(see example 5 and 7).

For example, a community with 10 species and 15 resources can have a `trophic_preferences` like `list(c(rep(1,5), rep(-1,5), rep(0,5), NULL, NULL)` for 3 trophic levels (`length(trophic_levels) = 3` ), indicating that the first (top) trophic level prefers to use first 5 resources and to produce the 6th-10th, and leaving the last 5 resources untouched.

must have same length as `trophic_levels` . If a shorter `trophic_preferences` was given, `NULL` s will be automatically added at tail.

**`exact`**: `boolean`

whether the number of resources to consume and to produce (`mean_consumption` and `mean_production`) should equal to the given value for each species. By default is `FALSE` : `mean_consumption` and `mean_production` only control the expected average value.

### simulateConsumerResource

#### basics

**`n_species`** : `Integer`

number of species in community

**`n_resources`** : `integer`

number of compounds that are either consumed or produced by the community members

#### customize

**`names_species`** : `character vector`

names of species to use during the simulation. If not provided, species are named as *sp1, sp2, ...*

must have same length as `n_species`

**`names_resources`** : `character vector`

names of compounds to use during the simulation. If not provided, compounds are named as *res1, res2, ...*

must have same length as `n_resources`

#### Matrix of biotic-abiotic conversion

**`E`** : `numeric matrix`

matrix of efficiency. A matrix defining the efficiency of resource-to-biomass conversion (positive values) and the relative conversion of metabolic by-products (negative values). It is recommended to be generated using the function `randomE`

must have dimension as `(n_species, n_resources)`

#### initial state

**`x0`** : `numeric`

initial abundances of species. If not provided, then a draw from uniform distribution from 0.1 to 10 is used as the initial abundances of species.

must have same length as `n_species`

**`resources`** : `numeric`

initial concentrations of compounds to use during the simulation. If not provided, then a draw from uniform distribution from 1 to 100 is used as the initial concentration of resources.

must have same length as `n_resources`

#### growth of microorganisms

**`growth_rates`** : `numeric`

maximum growth rates of species. In this consumer-resource model, this variable is the $\mu$ in aforementioned equation. If not provided, then 1 is used for all species.

must have same length as `n_species`

**`monod constant`** : `numeric matrix`

matrix of monod constant. A matrix defining the $k_{i,j}$ in the Monod equation. The default value is a draw from a gamma distribution with 50 times of maximum initial concentration as alpha and 1 as beta.

must have dimension as `(n_species, n_resources)`

#### stochasticity

**`stochastic`**: `boolean`

whether to include stochasticity in the simulation. By default `stochastic` is `FALSE` .

**`sigma_drift`**: `numeric`

strengths of ecological drift which happens on each step in the simulation. By default is 0.001, indicating the standard deviation of a normally distributed noise.

Controlled by `stochastic` .

**`sigma_epoch`** : `numeric`

strength of intrinsic fluctuations of community. By default is 0.1. This stochastic epoch event is not continuous and the probability/frequency is controlled by `epoch_p` .

Controlled by `stochastic` .

**`epoch_p`** : `numeric`

probability/frequency of intrinsic random periodic changes introduced to the community composition. By default is 0.001.

Controlled by `stochastic` .

**`sigma_external`** : `numeric`

strength of external disturbances happening on the given time points. Time points are defined using `t_external_events` and `t_external_durations` . By default is 0.3

Controlled by `stochastic` .

**`t_external_events`** : `numeric vector`

starting time points of external disturbances. By default there's no external events.

Controlled by `stochastic` .

must have same length as `t_external_durations`

**`t_external_durations`** : `numeric vector`

durations of external disturbances. By default there's no external events.

Controlled by `stochastic` .

must have same length as `t_external_events`

**`migration_p`** : `numeric`

probability/frequency of migration of certain individuals from a metacommunity in each time step of the simulation. The strength of migration is controlled by `sigma_migration` . By default is 0.01

Controlled by `stochastic` .

**`sigma_migration`** : `numeric`

intensity of migration at each time step. By default is 0.01

**`metacommunity_probability`** : `numeric vector`

the probability distribution of likelihood that species from the metacommunity can enter the community during the simulation. If not given, `n_species` of numbers will be drawn from a dirichlet distribution which alpha = 1.

must have same length as `n_species` .

**`error_variance`** : `numeric`

the variance of measurement error. By default is 0, indicating that the result won't contain any measurement error.

This value must be non-negative.

**`norm`** : `boolean`

whether the returned result should be normalized (return relative abundances for species in the community). By default is `FALSE` .

#### trophic priority

**`trophic priority`** : `matrix`

a matrix defining the orders of resources to be consumed by each species. For each row(species), the resource corresponding to largest value in this row will be first consumed (if not run out), and other resources, even their corresponding value in the matrix of efficiency `E` is positive (means consuming), would not be consumed unless all resources with higher priority are run out. By default this feature is not enabled, and all resources with a positive E value for one species will be consumed simultaneously.

If enabled, please be attention to avoid the situation that several species consumes less than their production in total. Otherwise this will lead to the explosion in the simulation.

must have same dimension as matrix of efficiency `E` .

#### time control

**`t_end`** : `numeric`

the final time of the simulation. If not given, by default is 1000.

**`t_start`** : `numeric`

the starting time of the simulation. If not given, by default is 0. Must be less than `t_end`

**`t_step`** : `numeric`

the time interval for each step of calculation. If not given, by default is 0.1

**`t_store`** : `numeric`

the number of time points to store/export for the whole simulation. If not given, by default is 1000. Note that must be less than `(t_end - t_start)/t_step` .
